# Generated by Django 4.0.10 on 2023-03-17 08:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0003_alter_organization_members'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='statustype',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='statustype',
            name='organization',
        ),
        migrations.RemoveField(
            model_name='tasktype',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='tasktype',
            name='organization',
        ),
        migrations.DeleteModel(
            name='PriorityType',
        ),
        migrations.DeleteModel(
            name='StatusType',
        ),
        migrations.DeleteModel(
            name='TaskType',
        ),
    ]
