# Generated by Django 4.0.10 on 2023-03-18 07:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0001_initial'),
        ('org_management', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasktype',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='type', to='organization.organization'),
        ),
    ]
