# Generated by Django 4.0.10 on 2023-03-15 08:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sprint', '0002_alter_sprint_project'),
        ('task', '0002_alter_task_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='sprint',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sprint.sprint'),
        ),
    ]
